#!/bin/bash
export DOCKER_BUILDKIT=0
if [ "$1" == "all" ] ; then
  docker compose --env-file server.env build --no-cache "tactic_base"
  docker compose --env-file server.env build --no-cache "tactic_host"
  docker compose --env-file server.env build --no-cache "tactic_main"
	docker compose --env-file server.env build --no-cache "tactic_module_viewer"
	docker compose --env-file server.env build --no-cache "tactic_tile"
	docker compose --env-file server.env build --no-cache "tactic_pool_watcher_s3"
	docker compose --env-file server.env build --no-cache "tactic_mongo_watcher"
	docker compose --env-file server.env build --no-cache "tactic_log_streamer"
	docker compose --env-file server.env build --no-cache "tactic_assistant"
else
	docker compose --env-file server.env --profile build_project build --no-cache "tactic_$1"
fi