#!/bin/bash

# Dynamically find ROOT_DIR (directory named 'tactic' above the current dir)
PROJECT_DIR=$(cd "$(dirname "$0")" && pwd)
while [[ "$PROJECT_DIR" != "/" && "$(basename "$PROJECT_DIR")" != "tactic" ]]; do
  PROJECT_DIR=$(dirname "$PROJECT_DIR")
done

if [[ "$(basename "$PROJECT_DIR")" != "tactic" ]]; then
  echo "Error: Could not find 'tactic' directory."
  exit 1
fi

export ROOT_DIR="$PROJECT_DIR"
echo "Using ROOT_DIR=$ROOT_DIR"

# shellcheck disable=SC2164
cd "$ROOT_DIR"

# Run docker compose based on argument
if [ "$1" == "all" ] ; then
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build
elif [ "$1" == "non_base" ] ; then
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_host"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_main"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_module_viewer"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_tile"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_log_streamer"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_assistant"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_mongo_watcher"
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_pool_watcher"

elif [ "$1" == "host" ] ; then
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_host1"
else
  sudo ROOT_DIR="$ROOT_DIR" DOCKER_BUILDKIT=0 docker compose --env-file develop.env --profile build_project build "tactic_$1"
fi