#!/bin/bash

# Dynamically find ROOT_DIR (directory named 'tactic' above the current dir)
PROJECT_DIR=$(cd "$(dirname "$0")" && pwd)
while [[ "$PROJECT_DIR" != "/" && "$(basename "$PROJECT_DIR")" != "tactic" ]]; do
  PROJECT_DIR=$(dirname "$PROJECT_DIR")
done

if [[ "$(basename "$PROJECT_DIR")" != "tactic" ]]; then
  echo "Error: Could not find 'tactic' directory."
  exit 1
fi

export ROOT_DIR="$PROJECT_DIR"
echo "Using ROOT_DIR=$ROOT_DIR"
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=2

# shellcheck disable=SC2164
cd "$ROOT_DIR"

SERVICES=(
  "tactic_host1"
  "tactic_main"
  "tactic_module_viewer"
  "tactic_pool_watcher_s3"
  "tactic_mongo_watcher"
  "tactic_log_streamer"
  "tactic_assistant"
)

if [ "$1" == "non_base" ] ; then
  for SERVICE in "${SERVICES[@]}"; do
    ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env build "$SERVICE"
  done
  ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env build "tactic_tile"

elif [ "$1" == "base" ] ; then
  ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env --profile build build "tactic_base"

elif [ "$1" == "wheels" ] ; then
  ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env --profile build build "tactic_wheels"

elif [ "$1" == "host" ] ; then
  ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env build "tactic_host1"
else
  ROOT_DIR="$ROOT_DIR" docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file develop.env build "tactic_$1"
fi