ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./module_viewer_container_env/requirements.txt /code/module_viewer_container_env/requirements.txt
RUN pip install -r /code/module_viewer_container_env/requirements.txt
RUN pip install structlog python-json-logger
LABEL maintainer="Bruce L Sherin"
ADD ./shared_mongo_python /code
ADD  ./module_viewer_container_env /code/module_viewer_container_env
ADD  ./shared_python /code/shared_python
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code:/code/module_viewer_container_env:/code/shared_python
CMD ["python", "-u", "-m", "module_viewer_container_env.module_viewer_main"]