ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./log_streamer_env/requirements.txt /code/log_streamer_env/requirements.txt
RUN pip install -r /code/log_streamer_env/requirements.txt
RUN pip install structlog python-json-logger
ADD ./log_streamer_env /code/log_streamer_env
ADD  ./shared_python/ /code/shared_python
LABEL maintainer="Bruce L Sherin"
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code:/code/log_streamer_env:/code/shared_python
# RUN python -m pip install --no-cache-dir "pydevd-pycharm==253.28086.55"
CMD ["python", "-u", "-m", "log_streamer_env.log_streamer_main"]