ARG BASE_IMAGE=bsherin/tactic:base
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./log_streamer_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD ./log_streamer_env /code
LABEL maintainer="Bruce L Sherin"
CMD ["python", "-u", "log_streamer.py"]