ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./mongo_watcher_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD ./mongo_watcher_env /code
ADD  ./shared_python/exception_mixin.py /code/
LABEL maintainer="Bruce L Sherin"
ADD ./shared_python/mongo_db_fs.py /code/
CMD ["python", "-u", "mongo_watcher.py"]