ARG BASE_IMAGE=bsherin/tactic:base
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./pool_container_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD  ./pool_container_env /code/
LABEL maintainer="Bruce L Sherin"
CMD ["python", "-u", "pool_watcher.py"]