ARG BASE_IMAGE=bsherin/tactic:base
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./module_viewer_container_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
LABEL maintainer="Bruce L Sherin"
ADD  ./module_viewer_container_env ./shared_python/exception_mixin.py ./shared_python/tactic_copilot_mixin.py ./shared_python/qworker.py ./shared_python/communication_utils.py ./shared_python/mongo_db_fs.py /code/
CMD ["python", "-u", "module_viewer_main.py"]