ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./main_container_env/requirements.txt /code/main_container_env/requirements.txt
RUN pip install -r /code/main_container_env/requirements.txt
RUN pip install structlog python-json-logger
LABEL maintainer="Bruce L Sherin"
ADD ./main_container_env /code/main_container_env
ADD ./shared_python /code/shared_python
ADD ./shared_mongo_python /code/shared_mongo_python
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code:/code/main_container_env:/code/shared_python:/code/shared_mongo_python
# RUN python -m pip install --no-cache-dir "pydevd-pycharm==253.28086.55"
CMD ["python", "-u", "-m", "main_container_env.main_main"]