ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./assistant_container_env/requirements.txt /code/assistant_container_env/requirements.txt
RUN pip install -r /code/assistant_container_env/requirements.txt
RUN pip install structlog python-json-logger
LABEL maintainer="Bruce L Sherin"
ADD  ./assistant_container_env /code/assistant_container_env
ADD ./shared_python /code/shared_python
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code:/code/assistant_container_env:/code/shared_python
CMD ["python", "-u", "-m", "assistant_container_env.assistant"]