services:

  tactic-mongo:
    image: mongo:5.0
    hostname: ${MONGO_URI}
    container_name: ${MONGO_URI}
    command: >
      --bind_ip 0.0.0.0
      --replSet rs0
    labels:
      project: tactic_aux
    restart: always
    profiles:
      - start_project
      - start_development
      - start_mongo_only
    networks:
      - tactic-net
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DIR}:/data/db
      - ./dump:/dump

  tactic-redis:
    image: redis:alpine
    restart: always
    labels:
      project: tactic_aux
    hostname: tactic-redis
    container_name: tactic-redis
    profiles:
      - start_development
    networks:
      - tactic-net
    ports:
      - "6379:6379"
    environment:
      - MY_ID=tactic-redis
      - OWNER=host
    command: ["redis-server", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--dir", "/data"]
    volumes:
      - tactic-redis-data:/data

  megaplex:
    image: rabbitmq:3.12-management
    labels:
      project: tactic_aux
    depends_on:
      - tactic-redis
    restart: always
    profiles:
      - start_development
    hostname: megaplex
    container_name: megaplex
    networks:
      - tactic-net
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - MY_ID=megaplex
      - OWNER=host

  tactic_base:
    build:
      context: .
      dockerfile: Dockerfile-base
    profiles:
      - build_project
      - build_server_project
    image: bsherin/tactic-base:${IMG_SUFFIX}
    platform: ${PLATFORM}

  tactic_wheels:
    build:
      context: .
      dockerfile: Dockerfile-wheels
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    profiles:
      - build_project
      - build_server_project
    image: bsherin/tactic-wheels:${IMG_SUFFIX}
    platform: ${PLATFORM}
    environment:
      - PYTHONUNBUFFERED=0

  tactic_host1:
    build:
      context: .
      dockerfile: Dockerfile-host
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    profiles:
      - start_project
      - start_development
      - build_project
      - build_server_project
      - build_non_base
      - start_host
    image: bsherin/tactic-host:${IMG_SUFFIX}
    restart: on-failure
    ports:
      - "80:5000"
    hostname: none
    container_name: tactic_host5000
    platform: ${PLATFORM}
    init: true
    labels:
      project: tactic
      my_id: host5000
      owner: host
      parent: host
      other_name: none
    env_file:
      - ${ROOT_DIR}/env.list
    environment:
      - MY_ID=host5000
      - MONGO_URI=${MONGO_URI}
      - MYPORT=5000
      - TRUE_HOST_PERSIST_DIR=${ROOT_DIR}/persist
      - TRUE_HOST_RESOURCES_DIR=${ROOT_DIR}/resources
      - TRUE_HOST_POOL_DIR=${POOL_DIR}
      - USE_ARM64=${USE_ARM64}
      - DEVELOP=${DEVELOP}
      - ANYONE_CAN_REGISTER=${ANYONE_CAN_REGISTER}
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_S3=${USE_S3}
      - USE_GEVENT=True
      - RECYCLE_TILES=${RECYCLE_TILES}
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: bind
        source: "${ROOT_DIR}/persist"
        target: "/code/persist"
      - type: bind
        source: "${POOL_DIR}"
        target: "/pool"
      - type: bind
        source: "${ROOT_DIR}/static"
        target: "/code/static"
    networks:
      - tactic-net

  tactic_host2:
    image: bsherin/tactic-host:${IMG_SUFFIX}
    profiles:
      - unused
    restart: on-failure
    ports:
      - "5001:5000"
    hostname: none
    container_name: tactic_host5001
    platform: ${PLATFORM}
    init: true
    labels:
      project: tactic
      my_id: host5001
      owner: host
      parent: host
      other_name: none
    env_file:
      - "${ROOT_DIR}/env.list"
    environment:
      - MY_ID=host5001
      - MONGO_URI=${MONGO_URI}
      - MYPORT=5001
      - TRUE_HOST_PERSIST_DIR=${ROOT_DIR}/persist
      - TRUE_HOST_RESOURCES_DIR=${ROOT_DIR}/resources
      - TRUE_HOST_POOL_DIR=${POOL_DIR}
      - USE_ARM64=${USE_ARM64}
      - DEVELOP=${DEVELOP}
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_S3=${USE_S3}
      - USE_GEVENT=True
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: bind
        source: "${ROOT_DIR}/persist"
        target: "/code/persist"
      - type: bind
        source: "${POOL_DIR}"
        target: "/pool"
      - type: bind
        source: "${ROOT_DIR}/static"
        target: "/code/static"
    networks:
      - tactic-net

  tile_test_container:
    image: bsherin/tactic-tile:${IMG_SUFFIX}
    depends_on:
      - tactic_host1
    profiles:
      - start_project
      - start_development
    restart: always
    init: true
    container_name: tile_test_container
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: tile_test_container
      owner: host
      parent: host
      other_name: tile_test_container
    env_file:
      - "${ROOT_DIR}/env.list"
    environment:
      - MY_ID=tile_test_container
      - PPI=0
      - MONGO_URI=${MONGO_URI}
      - OWNER=host
      - PARENT=host
      - USERNAME=
      - TRUE_HOST_PERSIST_DIR=${ROOT_DIR}/persist
      - TRUE_HOST_RESOURCES_DIR=${ROOT_DIR}/resources
      - NLTK_DATA=nltk_cache
      - HF_HOME=hf_cache
      - TRANSFORMERS_CACHE=hf_cache
      - TORCH_HOME=torch_cache
      - MPLCONFIGDIR=mpl_cache
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=False
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_S3=${USE_S3}
      - USE_GEVENT=False
    volumes:
      - type: bind
        source: ${ROOT_DIR}/persist
        target: "/code/persist"
      - type: bind
        source: ${ROOT_DIR}/resources
        target: "/root/resources"
      - type: bind
        source: ${ROOT_DIR}/resources/huggingface
        target: "/root/.cache/huggingface"
    networks:
      - tactic-net

  tactic_log_streamer:
    build:
      context: .
      dockerfile: Dockerfile-log-streamer
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    profiles:
      - build_project
      - build_server_project
      - build_non_base
      - start_project
      - start_development
    image: bsherin/tactic-log-streamer:${IMG_SUFFIX}
    container_name: tactic_log_streamer
    platform: ${PLATFORM}
    env_file:
      - "${ROOT_DIR}/env.list"
    labels:
      project: tactic
      my_id: tactic_log_streamer
      owner: host
      parent: host
      other_name: tactic_log_streamer
    environment:
      - PYTHONUNBUFFERED=0
      - MY_ID=log_streamer
      - OWNER=host
      - PARENT=host
      - AWS_ACCOUNT=${AWS_ACCOUNT}
      - MONGO_URI=${MONGO_URI}
      - USE_ARM64=${USE_ARM64}
      - DEVELOP=${DEVELOP}
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_S3=${USE_S3}
      - USE_GEVENT=True
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    networks:
      - tactic-net

  tactic_assistant:
    build:
      context: .
      dockerfile: Dockerfile-assistant
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    profiles:
      - build_project
      - build_server_project
      - build_non_base
    image: bsherin/tactic-assistant:${IMG_SUFFIX}
    platform: ${PLATFORM}
    environment:
      - PYTHONUNBUFFERED=0
      - USE_GEVENT=False
      - DEBUG=${DEBUG}

  tactic_mongo_watcher:
    image: bsherin/tactic-mongo-watcher:${IMG_SUFFIX}
    build:
      context: .
      dockerfile: Dockerfile-mongo-watcher
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    profiles:
      - start_project
      - start_development
      - build_project
      - build_server_project
      - build_non_base
    restart: always
    container_name: mongo_watcher
    init: true
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: mongo_watcher
      owner: host
      parent: host
      other_name: mongo_watcher
    environment:
      - MONGO_URI=${MONGO_URI}
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
    networks:
     - tactic-net

  tactic_pool_watcher:
    image: bsherin/tactic-pool-watcher:${IMG_SUFFIX}
    profiles:
      - build_project
      - build_non_base
    build:
      context: .
      dockerfile: Dockerfile-pool-watcher
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    restart: always
    container_name: pool_watcher
    init: true
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: pool_watcher
      owner: host
      parent: host
      other_name: pool_watcher
    environment:
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
    volumes:
      - type: bind
        source: "${POOL_DIR}"
        target: "/pool"
    networks:
      - tactic-net

  tactic_pool_watcher_s3:
    image: bsherin/tactic-pool-watcher-s3:${IMG_SUFFIX}
    profiles:
      - start_development
      - build_server_project
      - build_non_base
    build:
      context: .
      dockerfile: Dockerfile-pool-watcher-s3
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    restart: always
    container_name: pool_watcher_s3
    init: true
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: pool_watcher_s3
      owner: host
      parent: host
      other_name: pool_watcher_s3
    environment:
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
    networks:
      - tactic-net

  tactic_main:
    build:
      context: .
      dockerfile: Dockerfile-main
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: bsherin/tactic-main:${IMG_SUFFIX}
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: main_service
      owner: host
      parent: host
      other_name: main_service
    profiles:
      - build_project
      - start_development
      - build_server_project
      - build_non_base
    env_file:
      - ${ROOT_DIR}/env.list
    environment:
      - MY_ID=main_service
      - MONGO_URI=${MONGO_URI}
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - USE_ECS_TILES=${USE_ECS_TILES}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_S3=${USE_S3}
      - USE_GEVENT=False
      - DEBUG=${DEBUG}
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    networks:
      - tactic-net

  tactic_module_viewer:
    build:
      context: .
      dockerfile: Dockerfile-module-viewer
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    platform: ${PLATFORM}
    labels:
      project: tactic
      my_id: module_viewer
      owner: host
      parent: host
      other_name: module_viewer
    image: bsherin/tactic-module-viewer:${IMG_SUFFIX}
    profiles:
      - build_project
      - build_server_project
      - build_non_base
      - start_development
    env_file:
      - "${ROOT_DIR}/env.list"
    environment:
      - PYTHONUNBUFFERED=0
      - MY_ID=module_viewer
      - MONGO_URI=${MONGO_URI}
      - OWNER=host
      - PARENT=host
      - USE_AMAZON_MQ=${USE_AMAZON_MQ}
      - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      - USE_GEVENT=False
    networks:
      - tactic-net
  tactic_tile:
    build:
      context: .
      dockerfile: Dockerfile-tile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        WHEELS_IMAGE: ${WHEELS_IMAGE}
    depends_on:
      - tactic_wheels
    image: bsherin/tactic-tile:${IMG_SUFFIX}
    platform: ${PLATFORM}
    profiles:
      - build_project
      - build_non_base
    environment:
      - HF_HOME=/var/cache/hf
      - NLTK_DATA=/root/nltk
      - MPLCONFIGDIR=/var/cache/matplotlib
      - TORCH_HOME=/var/cache/torch
      - PYTHONUNBUFFERED=0
networks:
  tactic-net:
    driver: bridge
    external: true

volumes:
  hf_cache:
    external: true
  nltk_cache:
    external: true
  mpl_cache:
    external: true
  torch_cache:
    external: true
  tmp:
    external: true
  mongo-volume:
    external: true
  tactic-redis-data: