ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /code
ADD ./mongo_watcher_env/requirements.txt /code/mongo_watcher_env/requirements.txt
RUN pip install -r /code/mongo_watcher_env/requirements.txt
RUN pip install structlog python-json-logger
ADD ./mongo_watcher_env /code/mongo_watcher_env
ADD ./shared_python /code/shared_python
ADD ./shared_mongo_python /code/shared_mongo_python
LABEL maintainer="Bruce L Sherin"
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code:/code/mongo_watcher_env:/code/shared_python:/code/shared_mongo_python
CMD ["python", "-u", "-m", "mongo_watcher_env.mongo_watcher"]