
services:

    grafana:
      image: grafana/grafana:10.4.3
      ports:
        - "127.0.0.1:3000:3000"
      labels:
        project: tactic_aux
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana-data:/var/lib/grafana
      networks:
        - tactic-net

    tactic-mongo:
      image: mongo:5.0
      hostname: tactic-mongo
      container_name: tactic-mongo
      command: >
        --bind_ip 0.0.0.0
        --replSet rs0
      restart: always
      networks:
        - tactic-net
      ports:
        - "27017:27017"
      volumes:
        - ${MONGO_DIR}:/data/db
        - ./dump:/dump

    tactic_base:
      build:
        context: .
        dockerfile: Dockerfile-base
      profiles: ["build"]
      image: bsherin/tactic-base:${IMG_SUFFIX}
      platform: ${PLATFORM}

    tactic_wheels:
      build:
        context: .
        dockerfile: Dockerfile-wheels
        args:
          BASE_IMAGE: ${BASE_IMAGE}
      profiles: ["build"]
      image: bsherin/tactic-wheels:${IMG_SUFFIX}
      platform: ${PLATFORM}
      environment:
        - PYTHONUNBUFFERED=0

    tactic_host1:
      build:
        context: .
        dockerfile: Dockerfile-host
        args:
          BASE_IMAGE: ${BASE_IMAGE}
      image: bsherin/tactic-host:${IMG_SUFFIX}
      restart: on-failure
      ports:
        - "5000:5000"
      hostname: none
      container_name: tactic_host5000
      platform: ${PLATFORM}
      init: true
      labels:
        project: tactic
        my_id: host5000
        owner: host
        parent: host
        other_name: none
      environment:
        - MY_ID=host5000
        - MYPORT=5000
        - USE_DEVELOPMENT_BUNDLES=${USE_DEVELOPMENT_BUNDLES}
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
        - USE_GEVENT=True
        - PYCHARM_DEBUG=1
      volumes:
        - type: bind
          source: "/var/run/docker.sock"
          target: "/var/run/docker.sock"
        - type: bind
          source: "${ROOT_DIR}/persist"
          target: "/code/persist"
        - type: bind
          source: "${POOL_DIR}"
          target: "/pool"
        - type: bind
          source: "${ROOT_DIR}/static"
          target: "/code/host_container_env/static"
      networks:
        - tactic-net

    tile_test_container:
      image: bsherin/tactic-tile:${IMG_SUFFIX}
      restart: always
      init: true
      container_name: tile_test_container
      platform: ${PLATFORM}
      labels:
        project: tactic
        my_id: tile_test_container
        owner: host
        parent: host
        other_name: tile_test_container
      environment:
        - MY_ID=tile_test_container
        - PPI=0
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
        - OWNER=host
        - PARENT=host
        - NLTK_DATA=nltk_cache
        - HF_HOME=hf_cache
        - TRANSFORMERS_CACHE=hf_cache
        - TORCH_HOME=torch_cache
        - MPLCONFIGDIR=mpl_cache
        - USE_GEVENT=False
      volumes:
        - type: bind
          source: ${ROOT_DIR}/persist
          target: "/code/persist"
        - type: bind
          source: ${ROOT_DIR}/resources
          target: "/root/resources"
        - type: bind
          source: ${ROOT_DIR}/resources/huggingface
          target: "/root/.cache/huggingface"
      networks:
        - tactic-net

    tactic_log_streamer:
      build:
        context: .
        dockerfile: Dockerfile-log-streamer
        args:
          BASE_IMAGE: ${BASE_IMAGE}
      image: bsherin/tactic-log-streamer:${IMG_SUFFIX}
      container_name: tactic_log_streamer
      platform: ${PLATFORM}
      labels:
        project: tactic
        my_id: tactic_log_streamer
        owner: host
        parent: host
        other_name: tactic_log_streamer
      environment:
        - PYTHONUNBUFFERED=0
        - MY_ID=log_streamer
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
        - OWNER=host
        - PARENT=host
        - DEVELOP=${DEVELOP}
        - USE_GEVENT=False
      volumes:
        - type: bind
          source: "/var/run/docker.sock"
          target: "/var/run/docker.sock"
      networks:
        - tactic-net

    tactic_assistant:
      build:
        context: .
        dockerfile: Dockerfile-assistant
        args:
          BASE_IMAGE: ${BASE_IMAGE}
      labels:
        project: tactic
        my_id: assistant
        owner: host
        parent: host
        other_name: assistant
      image: bsherin/tactic-assistant:${IMG_SUFFIX}
      platform: ${PLATFORM}
      environment:
        - PYTHONUNBUFFERED=0
        - DEBUG=${DEBUG}
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
        - MY_ID=assistant
        - OWNER=host
        - PARENT=host
        - DEVELOP=${DEVELOP}
        - USE_GEVENT=False
      volumes:
        - type: bind
          source: "/var/run/docker.sock"
          target: "/var/run/docker.sock"
      networks:
        - tactic-net

    tactic_mongo_watcher:
      image: bsherin/tactic-mongo-watcher:${IMG_SUFFIX}
      build:
        context: .
        dockerfile: Dockerfile-mongo-watcher
        args:
          BASE_IMAGE: ${BASE_IMAGE}
      restart: always
      container_name: mongo_watcher
      init: true
      platform: ${PLATFORM}
      labels:
        project: tactic
        my_id: mongo_watcher
        owner: host
        parent: host
        other_name: mongo_watcher
      environment:
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
      networks:
        - tactic-net

    tactic_tile:
      build:
        context: .
        dockerfile: Dockerfile-tile
        args:
          BASE_IMAGE: ${BASE_IMAGE}
          WHEELS_IMAGE: ${WHEELS_IMAGE}
      depends_on:
        - tactic_wheels
      image: bsherin/tactic-tile:${IMG_SUFFIX}
      labels:
        project: tactic
        other_name: tile_service
      platform: ${PLATFORM}
      profiles: ["build"]
      environment:
        - HF_HOME=/var/cache/hf
        - NLTK_DATA=/root/nltk
        - MPLCONFIGDIR=/var/cache/matplotlib
        - TORCH_HOME=/var/cache/torch
        - PYTHONUNBUFFERED=0
        - RUNNING_ON_AWS=${RUNNING_ON_AWS}
networks:
  tactic-net:
    driver: bridge
    external: true

volumes:
  alloy-data:
  grafana-data:
  hf_cache:
    external: true
  nltk_cache:
    external: true
  mpl_cache:
    external: true
  torch_cache:
    external: true
  tmp:
    external: true
  mongo-volume:
    external: true
  tactic-redis-data:
  loki-data:
