
services:
  tactic_host1:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /tactic/ec2
        awslogs-create-group: "true"
        awslogs-stream: tactic_host1

  tactic_assistant:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /tactic/ec2
        awslogs-create-group: "true"
        awslogs-stream: tactic_assistant

  tile_test_container:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /tactic/ec2
        awslogs-create-group: "true"
        awslogs-stream: tactic_tile_test_container

  tactic_log_streamer:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /tactic/ec2
        awslogs-create-group: "true"
        awslogs-stream: tactic_log_streamer

  tactic_mongo_watcher:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: /tactic/ec2
        awslogs-create-group: "true"
        awslogs-stream: tactic_mongo_watcher