site_name: Tactic Documentation
repo_url: https://github.com/bsherin/tactic
pages:
- Home: 'Docs/index.md'
- Basics:
  - Getting Started: 'Docs/Getting-Started.md'
  - Resource Library:
    - Uploading Data: 'Docs/Uploading-Data.md'
  - Main Interface: 'Docs/Main-interface.md'
- Tile Programming Details:
  - Tile Structure: 'Docs/Tile-Structure.md'