site_name: Tactic Documentation
repo_url: https://github.com/bsherin/tactic
docs_dir: 'docs'
pages:
- Home: 'index.md'
- Basics:
  - Getting Started: 'Getting-Started.md'
  - Resource Library:
    - Uploading Data: 'Uploading-Data.md'
  - Main Interface: 'Main-interface.md'
  - Logs and Notebooks: "Log-And-Notebook.md"
  - Tile Creator: "Tile-Creator.md"
  - Module Viewer: "Module-Viewer.md"
  - Tile Version History and Compare: "Tile-Version-History-And-Compare.md"
  - Which tiles are available when: "Which-tiles-are-available-when.md"
- Tile Programming Details:
  - Tile Structure: 'Tile-Structure.md'
  - Matplotlib Tiles: "Matplotlib-Tiles.md"
  - D3 Tiles: "D3-Tiles.md"
  - Tile Commands:  "Tile-Commands.md"
  - Working with Code Resources: "Working-With-Code-Resources.md"
- Running Your Own Tactic Server: "Running-your-own-Tactic-server.md"