export {
    SIDE_MARGIN, ICON_BAR_WIDTH, STATUS_BAR_HEIGHT,
    BOTTOM_MARGIN, INIT_CONTEXT_PANEL_WIDTH
}

const SIDE_MARGIN = 15;
const BOTTOM_MARGIN = 35;
const STATUS_BAR_HEIGHT = 35;
const INIT_CONTEXT_PANEL_WIDTH = 250;
const ICON_BAR_WIDTH = 40;