user_data_fields = [
    {"name": "username",
     "editable": False,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": False,
     "withSettings": False,
     "default": None, "info_type": "system"},
    {"name": "alt_id",
     "editable": False,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": False,
     "withSettings": False,
     "default": None, "info_type": "system"},
    {"name": "status",
     "editable": False,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": False,
     "withSettings": False,
     "default": "active", "info_type": "system"},
    {"name": "email", "display_text": "email", "type": "text",
     "editable": True,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": True,
     "withSettings": False,
     "default": "", "info_type": "info"},
    {"name": "full_name", "display_text": "full name", "type": "text",
     "editable": True,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": True,
     "withSettings": False,
     "default": "", "info_type": "info"},
    {"name": "favorite_dumpling", "display_text": "favorite dumpling", "type": "text",
     "editable": True,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": True,
     "withSettings": False,
     "default": "", "info_type": "info"},
    {"name": "tzoffset",
     "editable": False,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": False,
     "withSettings": False,
     "default": None, "info_type": "system"},
    {"name": "theme", "display_text": "tactic theme",
     "editable": True,
     "settings_object": True,
     "settings_drawer": True,
     "account_page": True,
     "withSettings": True,
     "type": "select", "default": "dark", "options": ["dark", "light"], "info_type": "setting"},
    {"name": "preferred_dark_theme", "display_text": "codemirror dark theme",
     "editable": True,
     "settings_object": True,
     "settings_drawer": True,
     "account_page": True,
     "withSettings": True,
     "type": "select", "default": "nord", "options": ["material", "nord", "oceanic-next", "pastel-on-dark"],
     "info_type": "setting"},
    {"name": "preferred_light_theme", "display_text": "codemirror light theme",
     "editable": True,
     "settings_object": True,
     "settings_drawer": True,
     "account_page": True,
     "withSettings": True,
     "type": "select", "default": "default", "options": ["default", "elegant", "juejin", "neat", "solarized", "github"],
     "info_type": "setting"},
    {"name": "preferred_interface", "display_text": "preferred interface",
     "editable": True,
     "settings_object": True,
     "settings_drawer": True,
     "account_page": True,
     "withSettings": True,
     "type": "select", "default": "single-window", "options": ["separate-tabs", "single-window"],
     "info_type": "setting"},
    {"name": "openai_api_key", "display_text": "openai api key", "type": "text",
     "editable": True,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": True,
     "withSettings": False,
     "default": "", "info_type": "setting"},
     {"name": "show_line_numbers", "display_text": "show line numbers",
      "type": "select",
      "options": ["yes", "no"],
      "default": "yes",
      "editable": True,
      "settings_object": True,
      "settings_drawer": True,
      "account_page": True,
      "withSettings": True,
      "info_type": "setting"},
    {"name": "use_ai_code_suggestions", "display_text": "use ai code suggestions",
     "editable": True,
     "settings_object": True,
     "settings_drawer": True,
     "account_page": True,
     "withSettings": True,
     "type": "select", "options": ["yes", "no"], "default": False, "info_type": "setting"},
    {"name": "library_columns",
     "editable": False,
     "settings_object": False,
     "settings_drawer": False,
     "account_page": False,
     "withSettings": True,
     "default": ["created", "updated", "size"], }
]
