#!/bin/bash
if [ "$1" == "all" ] ; then
	DOCKER_BUILDKIT=0 docker-compose build "tactic_base"
	DOCKER_BUILDKIT=0 docker-compose build "tactic_host"
	DOCKER_BUILDKIT=0 docker-compose build "tactic_main"
	DOCKER_BUILDKIT=0 docker-compose build "tactic_module_viewer"
	DOCKER_BUILDKIT=0 docker-compose build "tactic_tile"
else
	DOCKER_BUILDKIT=0 docker-compose build "tactic_$1"
fi