#!/bin/bash
if [ "$1" == "all" ] ; then
	docker-compose build "tactic_base_arm64"
	docker-compose build "tactic_host_arm64"
	docker-compose build "tactic_main_arm64"
	docker-compose build "tactic_module_viewer_arm64"
	docker-compose build "tactic_tile_arm64"
else
	docker-compose build "tactic_$1_arm64"
fi