FROM bsherin/tactic:base
WORKDIR /code
ADD ./log_streamer_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD ./log_streamer_env /code
MAINTAINER "Bruce L Sherin"
CMD ["python", "-u", "log_streamer.py"]