FROM python:2.7.11
WORKDIR /code
ADD ./megaplex_container_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ADD  ./megaplex_container_env /code
CMD ["python", "-u", "megaplex_main.py"]