FROM tactic_base_image
WORKDIR /code
ADD ./module_viewer_container_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ADD  ./module_viewer_container_env /code
CMD ["python", "-u", "module_viewer_main.py"]