FROM tactic_base_image
WORKDIR /code
ADD ./tile_container_env/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
ADD  ./tile_container_env ./volume_manager.py ./exception_mixin.py ./redis_tools.py ./qworker.py ./communication_utils.py /code/
RUN apt-get update && apt-get -y install default-jre
RUN wget http://mallet.cs.umass.edu/dist/mallet-2.0.8.tar.gz && mkdir -p /opt/mallet && tar -xvzf mallet-2.0.8.tar.gz -C /opt/mallet --strip-components=1 && rm -f mallet-2.0.8.tar.gz
ENV PATH="${PATH}:/opt/mallet/bin"
CMD ["python", "-u", "tile_main.py"]
