version: '2'

services:
  tactic_base:
      build:
        context: .
        dockerfile: Dockerfile-base
      image: tactic_base_image

  tactic_megaplex:
    build:
      context: .
      dockerfile: Dockerfile-megaplex
    image: tactic_megaplex_image

  tactic_main:
    build:
      context: .
      dockerfile: Dockerfile-main
    image: tactic_main_image

  tactic_module_viewer:
    build:
      context: .
      dockerfile: Dockerfile-module-viewer
    image: module_viewer_image

  tactic_tile:
    build:
      context: .
      dockerfile: Dockerfile-tile
    image: tactic_tile_image
    environment:
      PYTHONUNBUFFERED: 0
