FROM bsherin/tactic:base
WORKDIR /code
ADD ./tile_container_env/requirements.txt /code/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get -y install default-jre
RUN wget http://mallet.cs.umass.edu/dist/mallet-2.0.8.tar.gz && mkdir -p /opt/mallet && tar -xvzf mallet-2.0.8.tar.gz -C /opt/mallet --strip-components=1 && rm -f mallet-2.0.8.tar.gz
ADD ./tile_container_env/new_requirements.txt /code/new_requirements.txt
RUN pip3 install --no-cache-dir -r new_requirements.txt
ADD ./tile_container_env/transformers_requirements.txt /code/transformers_requirements.txt
RUN pip3 install --no-cache-dir -r transformers_requirements.txt
ADD ./tile_container_env/newer_requirements.txt /code/newer_requirements.txt
RUN pip3 install --no-cache-dir -r newer_requirements.txt
ADD  ./tile_container_env ./volume_manager.py ./exception_mixin.py ./redis_tools.py ./rabbit_manage.py ./qworker.py ./communication_utils.py /code/
ADD ./tactic_dark.mplstyle /usr/local/lib/python3.11/site-packages/matplotlib/mpl-data/stylelib/
RUN pip3 install --no-cache-dir dask[complete]
# RUN pip install pydevd-pycharm~=213.5605.23
CMD ["python", "-u", "tile_main.py"]
