FROM tactic_base_image
WORKDIR /code
ADD ./dude_container_env /code
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ADD  ./volume_manager.py ./exception_mixin.py ./qworker.py ./communication_utils.py \
       ./docker_functions.py ./mongo_accesser.py /code/
EXPOSE 5000
CMD ["python", "-u", "dude_main.py"]