FROM python:3.7.1
WORKDIR /code
ADD  ./megaplex_container_env /code
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ENTRYPOINT ["/usr/local/bin/gunicorn", "-b", "0.0.0.0:5000", "megaplex_main:app"]
