FROM python:2.7.11
WORKDIR /code
ADD ./base_container_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ADD  ./base_container_env /code
ADD ./qworker.py /code
add ./communication_utils.py /code
