FROM tactic_base_image
WORKDIR /code
ADD ./tile_container_env/requirements-debug.txt /code/requirements-debug.txt
RUN pip install --no-cache-dir -r requirements-debug.txt
MAINTAINER "Bruce L Sherin"
ADD  ./tile_container_env /code
ADD ./pycharm-debug.egg /code
CMD ["python", "tile_main.py"]
