FROM tactic_base_image
WORKDIR /code
ADD ./main_container_env /code
RUN pip install -r requirements.txt
MAINTAINER "Bruce L Sherin"
ADD  ./volume_manager.py ./exception_mixin.py ./redis_tools.py ./qworker.py ./communication_utils.py \
./docker_functions.py ./mongo_accesser.py ./loaded_tile_management.py  ./rabbit_manage.py /code/
RUN pip install pydevd-pycharm~=193.5233.109
CMD ["python", "-u", "main_main.py"]