version: '2'

services:

  tactic_base:
      build:
        context: .
        dockerfile: Dockerfile-base
      image: tactic_base_image

  tactic_megaplex:
    build:
      context: .
      dockerfile: Dockerfile-megaplex
    image: tactic_megaplex_image
    environment:
      PYTHONUNBUFFERED: "Yes"

  tactic_main:
    build:
      context: .
      dockerfile: Dockerfile-main
    depends_on:
      - tactic_base
    image: tactic_main_image

  tactic_dude:
    build:
      context: .
      dockerfile: Dockerfile-dude
    depends_on:
      - tactic_base
    image: tactic_dude_image

  tactic_module_viewer:
    build:
      context: .
      dockerfile: Dockerfile-module-viewer
    depends_on:
      - tactic_base
    image: module_viewer_image

  tactic_tile:
    build:
      context: .
      dockerfile: Dockerfile-tile
    depends_on:
      - tactic_base
    image: tactic_tile_image
    environment:
      PYTHONUNBUFFERED: 0
