version: '3.7'

services:

  tactic_base:
      build:
        context: .
        dockerfile: Dockerfile-base
      image: bsherin/tactic:base

  tactic_host:
    build:
      context: .
      dockerfile: Dockerfile-host
    depends_on:
      - tactic_base
    image: bsherin/tactic:host
    environment:
      PYTHONUNBUFFERED: 1

  tactic_main:
    build:
      context: .
      dockerfile: Dockerfile-main
    depends_on:
      - tactic_base
    image: bsherin/tactic:main

  tactic_module_viewer:
    build:
      context: .
      dockerfile: Dockerfile-module-viewer
    depends_on:
      - tactic_base
    image: bsherin/tactic:module_viewer

  tactic_tile:
    build:
      context: .
      dockerfile: Dockerfile-tile
    depends_on:
      - tactic_base
    image: bsherin/tactic:tile
    environment:
      PYTHONUNBUFFERED: 0

  tactic_redis:
    image: redis:alpine

  tactic_rabbit:
    image: rabbitmq:3-management