version: '3.7'

services:

  tactic_base:
      build:
        context: .
        dockerfile: Dockerfile-base
      image: tactic_base_image

  tactic_host:
    build:
      context: .
      dockerfile: Dockerfile-host
    depends_on:
      - tactic_base
    image: tactic_host_image
    environment:
      PYTHONUNBUFFERED: 1

  tactic_main:
    build:
      context: .
      dockerfile: Dockerfile-main
    depends_on:
      - tactic_base
    image: tactic_main_image

  tactic_module_viewer:
    build:
      context: .
      dockerfile: Dockerfile-module-viewer
    depends_on:
      - tactic_base
    image: module_viewer_image

  tactic_tile:
    build:
      context: .
      dockerfile: Dockerfile-tile
    depends_on:
      - tactic_base
    image: tactic_tile_image
    environment:
      PYTHONUNBUFFERED: 0

  tactic_redis:
    image: redis:alpine

  tactic_rabbit:
    image: rabbitmq:3-management