FROM bsherin/tactic:base-arm64
WORKDIR /code
ADD ./log_streamer_env/requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD ./log_streamer_env /code
#RUN pip install pydevd-pycharm
MAINTAINER "Bruce L Sherin"
CMD ["python", "-u", "log_streamer.py"]